/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.UI;

import Main.Components.User;
import Main.ITSController;
import Main.UI.Components.VectorIconPanel;
import java.awt.Dimension;
import javax.json.JsonArray;
import javax.json.JsonObject;

/**
 *
 * @author crimsiris
 */
public class ChatWindow extends javax.swing.JFrame {

    private final int AVATAR_WIDTH=104;
    private final int AVATAR_HEIGHT=104;
    
    private final String JSON_KEY_DIALOGUE=Main.DialogueController.JSON_KEY_DIALOGUE;
    private final String JSON_KEY_REPLIES=Main.DialogueController.JSON_KEY_REPLIES;
    
    private ITSController controller;
    private User agent;
    private User currentUser;
    
    /**
     * Creates new form ChatWindow
     */
    public ChatWindow(ITSController controller, User user, User agent) {
        initComponents();
        
        initializeComponents(controller, user, agent);
    }
    
    private void initializeComponents(ITSController controller, User user, User agent)
    {
        this.controller=controller;
        
        this.currentUser=user;
        this.agent=agent;
        
        userAvatar.setPreferredSize(new Dimension(AVATAR_WIDTH, AVATAR_HEIGHT));
        userAvatar.setIcon(currentUser.getAvatarPath());
        userAvatar.repaint();
        lblUserName.setText(currentUser.getName());
        
        agentAvatar.setPreferredSize(new Dimension(AVATAR_WIDTH, AVATAR_HEIGHT));
        agentAvatar.setIcon((this.agent).getAvatarPath());
        agentAvatar.repaint();
        lblAgentName.setText(agent.getName());
        
        addListeners();
    }
    
    public void addListeners()
    {
        replyDialoguePanel.tblChoices.addMouseListener(this.controller);
        replyDialoguePanel.selfReportingPanel.happyPanel.addMouseListener(this.controller);
        replyDialoguePanel.selfReportingPanel.sadPanel.addMouseListener(this.controller);
    }
        
    public void initialize(JsonObject dialogue)
    {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        setDialogue(dialogue);
    }
    
    public void setDialogue(JsonObject dialogue)
    {           
        statementDialoguePanel.setText(dialogue.getString(JSON_KEY_DIALOGUE));
        replyDialoguePanel.setReplies(dialogue.getJsonArray(JSON_KEY_REPLIES));                 
    }
    
    public JsonObject getSelectedReply()
    {
        return replyDialoguePanel.getSelectedReply();
    }
            

    
    public void close()
    {
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        agentAvatar = new Main.UI.Components.VectorIconPanel();
        userAvatar = new Main.UI.Components.VectorIconPanel();
        statementDialoguePanel = new Main.UI.Components.StatementDialoguePanel();
        replyDialoguePanel = new Main.UI.Components.ReplyDialoguePanel();
        lblUserName = new javax.swing.JLabel();
        lblAgentName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        org.jdesktop.layout.GroupLayout agentAvatarLayout = new org.jdesktop.layout.GroupLayout(agentAvatar);
        agentAvatar.setLayout(agentAvatarLayout);
        agentAvatarLayout.setHorizontalGroup(
            agentAvatarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 104, Short.MAX_VALUE)
        );
        agentAvatarLayout.setVerticalGroup(
            agentAvatarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 104, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout userAvatarLayout = new org.jdesktop.layout.GroupLayout(userAvatar);
        userAvatar.setLayout(userAvatarLayout);
        userAvatarLayout.setHorizontalGroup(
            userAvatarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 104, Short.MAX_VALUE)
        );
        userAvatarLayout.setVerticalGroup(
            userAvatarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 104, Short.MAX_VALUE)
        );

        lblUserName.setFont(new java.awt.Font("Edmondsans", 0, 18)); // NOI18N
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText("jLabel1");

        lblAgentName.setFont(new java.awt.Font("Edmondsans", 0, 18)); // NOI18N
        lblAgentName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgentName.setText("jLabel1");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(agentAvatar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(28, 28, 28)
                                .add(lblAgentName)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(statementDialoguePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(replyDialoguePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(userAvatar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(31, 31, 31)
                                .add(lblUserName)))))
                .add(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, statementDialoguePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(8, 8, 8)
                        .add(agentAvatar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(4, 4, 4)
                        .add(lblAgentName)))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(26, 26, 26)
                        .add(userAvatar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(4, 4, 4)
                        .add(lblUserName))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(replyDialoguePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(27, 27, 27))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Main.UI.Components.VectorIconPanel agentAvatar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAgentName;
    private javax.swing.JLabel lblUserName;
    public Main.UI.Components.ReplyDialoguePanel replyDialoguePanel;
    private Main.UI.Components.StatementDialoguePanel statementDialoguePanel;
    private Main.UI.Components.VectorIconPanel userAvatar;
    // End of variables declaration//GEN-END:variables
}
