/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.UI;

import Main.Components.User;
import Main.ITSController;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author crimsiris
 */
public class LoginWindow extends javax.swing.JFrame {

    private final int AVATAR_WIDTH=160;
    private final int AVATAR_HEIGHT=160;
    
    private ITSController controller;
    
    private DefaultComboBoxModel names;
    private ArrayList<User> users;
    
    
    /**
     * Creates new form LoginWindow
     */
    public LoginWindow(ITSController controller, ArrayList<User> users) 
    {
        initComponents();
        
        initializeComponents(controller, users);
    }
    
    private void initializeComponents(ITSController controller, ArrayList<User> users) 
    {
        this.controller=controller;
        this.users=users;
        
        paintAvatar();
        
        names=new DefaultComboBoxModel();
        for(User u: users)
        {
            names.addElement(u.getName());
        }
        cmbNames.setModel(names);
        cmbNames.setEditable(false);
        
        addListeners();
    }
    
    private void addListeners()
    {
        cmbNames.addActionListener(this.controller);
        btnLogin.addActionListener(this.controller);
        btnSignup.addActionListener(this.controller);
        
    }
    
    public void initialize()
    {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    private String getAvatarPath()
    {
        int index=cmbNames.getSelectedIndex();
        User selectedUser=users.get(index);
        return selectedUser.getAvatarPath();
        
    }
    
    public void paintAvatar()
    {
        avatar.setPreferredSize(new Dimension(AVATAR_WIDTH, AVATAR_HEIGHT));
        
        String avatarPath=getAvatarPath();
        avatar.resetIconBGColor();
        avatar.setIcon(avatarPath);
        avatar.repaint();
    }
    
    public User getCurrentUser()
    {
        int index=cmbNames.getSelectedIndex();
        return users.get(index);
    }
    
    public void close()
    {
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        cmbNames = new javax.swing.JComboBox();
        btnSignup = new javax.swing.JButton();
        avatar = new Main.UI.Components.VectorIconPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnLogin.setFont(new java.awt.Font("Edmondsans", 0, 16)); // NOI18N
        btnLogin.setText("That's me!");

        cmbNames.setFont(new java.awt.Font("Edmondsans", 0, 18)); // NOI18N
        cmbNames.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbNames.setToolTipText("Click me and find your name");

        btnSignup.setFont(new java.awt.Font("Edmondsans", 0, 16)); // NOI18N
        btnSignup.setText("I'm new here!");

        org.jdesktop.layout.GroupLayout avatarLayout = new org.jdesktop.layout.GroupLayout(avatar);
        avatar.setLayout(avatarLayout);
        avatarLayout.setHorizontalGroup(
            avatarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 160, Short.MAX_VALUE)
        );
        avatarLayout.setVerticalGroup(
            avatarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 160, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(65, 65, 65)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(btnSignup, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, btnLogin, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, cmbNames, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(110, 110, 110)
                        .add(avatar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .add(avatar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(cmbNames, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(8, 8, 8)
                .add(btnLogin)
                .add(18, 18, 18)
                .add(btnSignup)
                .add(40, 40, 40))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Main.UI.Components.VectorIconPanel avatar;
    public javax.swing.JButton btnLogin;
    public javax.swing.JButton btnSignup;
    public javax.swing.JComboBox cmbNames;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
