/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.UI;

import Main.Components.User;
import Main.ITSController;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author crimsiris
 */
public class SignupWindow extends javax.swing.JFrame {
   
    private final int AVATAR_WIDTH=160;
    private final int AVATAR_HEIGHT=160;
    
    private ITSController controller;
    private ArrayList<String> allAvatarIDs;
    private HashMap<String, String> allAvatars;
    
    private int currentAvatarIndex=0;
    
    private ArrayList<String> genderList;
    private ArrayList<String> ageList;
    
    private DefaultComboBoxModel gender;
    private DefaultComboBoxModel age;
    
    /**
     * Creates new form SignupWindow
     */
    public SignupWindow(ITSController controller, HashMap<String, String> allAvatars) 
    {
        initComponents();
        
        initializeComponents(controller, allAvatars);
    }
    
    private void initializeComponents(ITSController controller, HashMap<String, String> allAvatars)
    {
        this.controller=controller;
        
        this.allAvatars=allAvatars;
        this.allAvatarIDs=new ArrayList<String>((this.allAvatars).keySet());
        paintAvatar();
        
        btnBack.setEnabled(false);
        
        txtName.setText("My name is..");
        
//        genderList=new ArrayList<String>();
//        genderList.add("I am a boy");
//        genderList.add("I am a girl");
//        
//        ageList=new ArrayList<String>();
//        ageList.add ("I am 8 now!");
//        ageList.add ("I am 9 now!");
//        ageList.add ("I am 10 now!");
//        
//        gender=new DefaultComboBoxModel();
//        for(String s: genderList)
//        {
//            gender.addElement(s);
//        }
//        cmbGender.setModel(gender);
//        cmbGender.setEditable(false);
//        
//        age=new DefaultComboBoxModel();
//        for(String s: ageList)
//        {
//            age.addElement(s);
//        }
//        cmbAge.setModel(age);
//        cmbAge.setEditable(false);
        
        addListeners();
    }
    
    private void paintAvatar()
    {       
        avatarPanel.setPreferredSize(new Dimension(AVATAR_WIDTH, AVATAR_HEIGHT));     
        repaintAvatar();
    }
    
    private void addListeners()
    {
        btnBack.addActionListener(this.controller);
        btnNext.addActionListener(this.controller);
        btnSignup.addActionListener(this.controller);
    }
    
    public void initialize()
    {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    } 
    
    private void repaintAvatar()
    {
        String avatarPath=getAvatarPath();
        avatarPanel.resetIconBGColor();
        avatarPanel.setIcon(avatarPath);
        avatarPanel.repaint();
    }
    
    public void showPreviousAvatar()
    {        
        currentAvatarIndex--;
        
        repaintAvatar();
        
        if (currentAvatarIndex==0)
            btnBack.setEnabled(false);
        
        if (!btnNext.isEnabled())
            btnNext.setEnabled(true);
        
    }
    
    public void showNextAvatar()
    {        
        currentAvatarIndex++;
        
        repaintAvatar();
        
        
        if (!btnBack.isEnabled())
            btnBack.setEnabled(true);
        
        if (currentAvatarIndex==allAvatarIDs.size()-1)
            btnNext.setEnabled(false);
        
    }
    
    public String getUsername()
    {
        return txtName.getText();
    }
    
    private String getAvatarPath()
    {
        return allAvatars.get(getAvatarID());
    }
    
    public String getAvatarID()
    {
        return allAvatarIDs.get(currentAvatarIndex);
    }
    
    
    public void close()
    {
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        btnSignup = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        avatarPanel = new Main.UI.Components.VectorIconPanel();
        avatar = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtName.setFont(new java.awt.Font("Edmondsans", 0, 18)); // NOI18N
        txtName.setText("jTextField1");

        btnSignup.setFont(new java.awt.Font("Edmondsans", 0, 16)); // NOI18N
        btnSignup.setText("I'm done!");

        btnBack.setText("<");
        btnBack.setToolTipText("Go back");

        btnNext.setText(">");
        btnNext.setToolTipText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout avatarPanelLayout = new org.jdesktop.layout.GroupLayout(avatarPanel);
        avatarPanel.setLayout(avatarPanelLayout);
        avatarPanelLayout.setHorizontalGroup(
            avatarPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 160, Short.MAX_VALUE)
        );
        avatarPanelLayout.setVerticalGroup(
            avatarPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 160, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(65, 65, 65)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(txtName)
                    .add(btnSignup, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(btnBack, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(avatarPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnNext, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(65, 65, 65))
            .add(jPanel1Layout.createSequentialGroup()
                .add(107, 107, 107)
                .add(avatar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(107, 107, 107))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(108, 108, 108)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(btnNext)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(btnBack)
                                .add(35, 35, 35)
                                .add(avatar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(avatarPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(18, 18, 18)
                .add(txtName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                .add(btnSignup)
                .add(40, 40, 40))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatar;
    private Main.UI.Components.VectorIconPanel avatarPanel;
    public javax.swing.JButton btnBack;
    public javax.swing.JButton btnNext;
    public javax.swing.JButton btnSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
