/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.UI;

import Main.ITSController;
import java.util.ArrayList;
import java.util.MissingFormatArgumentException;
import java.util.Random;

/**
 *
 * @author crimsiris
 */
public class WaitWindow extends javax.swing.JFrame {

    private final int ICON_WIDTH=80;
    
    private final int LABEL_WIDTH=180;
    
    private final String MESSAGE_WAIT="Oops! Can you please wait?";
    
    private ITSController controller;
    
    private ArrayList<String> cannedActivities;
    
    /**
     * Creates new form WaitWindow
     */
    public WaitWindow(ITSController controller, String agentName, char agentGender)
    {
        initComponents();
        initializeComponents(controller, agentName, agentGender);

    }
    
    private void initializeComponents(ITSController controller, String agentName, char agentGender)
    {
        this.controller=controller;
        
        cannedActivities=new ArrayList<String>();
        cannedActivities.add("%s is still feeling shy.");
        cannedActivities.add("%s is still in the bathroom.");
        cannedActivities.add("%s is just finishing %s snack.");
        cannedActivities.add("%s just went to drink water.");

        String followup="";
        
        try
        {
            followup=String.format(getRandomActivity(), agentName);
        }
        catch (MissingFormatArgumentException mfae)
        {
            followup=String.format(getRandomActivity(), agentName, getPossessiveNoun(agentGender));
        }
        
        
        
        infoPanel.updatePanel(MESSAGE_WAIT, followup, null, ICON_WIDTH, LABEL_WIDTH);
    }
    
    private String getRandomActivity()
    {
        Random r=new Random();
        int index=r.nextInt(cannedActivities.size());
        
        return cannedActivities.get(index);
    }
    
    private String getPossessiveNoun(char agentGender)
    {
        if (agentGender == 'F' || agentGender=='f')
        {
            return "her";
        }
        else 
            return "his";
    }
    
    public void initialize()
    {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
    }
    
    public void close()
    {
        this.dispose();
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        infoPanel = new Main.UI.Components.GeneralInfoPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(485, 222));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(485, 222));
        jPanel1.setSize(new java.awt.Dimension(485, 222));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(60, 60, 60)
                .add(infoPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 367, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(40, 40, 40)
                .add(infoPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(40, 40, 40))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 487, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 185, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Main.UI.Components.GeneralInfoPanel infoPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
