/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.UI.Components;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.JLabel;

/**
 *
 * @author crimsiris
 */
public class GeneralInfoPanel extends javax.swing.JPanel {

    private final String HTML_TEXT = "<html>" +
                                            "<div style=\"width:%dpx;padding-left:5px;text-align:justify;\">" +
                                                "<p style=\"font-family:Edmondsans;font-size:22px;\">%s</p>" +
                                            "</div>" +
                                          "</html>";
    
    private final String HTML_TEXT_AND_FOLLOWUP = "<html>" +
                                                    "<div style=\"width:%dpx;padding-left:5px;text-align:justify;\">" +
                                                        "<p style=\"font-family:Edmondsans;font-size:22px;\">%s</p>" +
                                                        "<p style=\"font-family:Edmondsans;font-size:12px;\">%s</p>" +
                                                    "</div>" +
                                                 "</html>";
    
    private final String HTML_TEXT_SMALLER = "<html>" +
                                                "<div style=\"width:%dpx;padding-left:4px;text-align:justify;\">" +
                                                    "<p style=\"font-family:Edmondsans;font-size:14px;\">%s</p>" +
                                                "</div>" +
                                              "</html>";
    
    private JLabel text;
    private VectorIconPanel icon;
    
    /**
     * Creates new form GeneralInfoPanel
     */
    public GeneralInfoPanel() 
    {
        initComponents();
        initializeComponents();
    }
    
    private void initializeComponents()
    {
        icon=new VectorIconPanel();
        
        text=new JLabel();
        text.setHorizontalAlignment(JLabel.LEADING);
        text.setVerticalAlignment(JLabel.CENTER);
        
        this.setLayout(new FlowLayout(FlowLayout.CENTER));
        this.setBackground(Color.WHITE);
        
        this.add(icon);
        this.add(text);
        
    }
    
    private String formatText(int labelWidth, String text, String subtitle)
    {
        return String.format(HTML_TEXT_AND_FOLLOWUP, labelWidth, text, subtitle);
    }
    
    private String formatText(int labelWidth, String text, boolean smallerText)
    {
        if (smallerText)
            return String.format(HTML_TEXT_SMALLER, labelWidth, text);
            
        return String.format(HTML_TEXT, labelWidth, text);
    }
    
    public void renderIcon(String iconPath, int iconWidth)
    {
        icon.resetIconBGColor();
        icon.setIcon(iconPath);
        icon.setPreferredSize(new Dimension(iconWidth, iconWidth));
        icon.repaint();
    }
    
    public void updatePanel(String text, String followup, String iconPath, int iconWidth, int labelWidth)
    {
        renderIcon (iconPath, iconWidth);
        
        String s=formatText(labelWidth, text, followup);

        this.text.setText(s);               
    }
    
    public void updatePanel(String text, String iconPath, int iconWidth, int labelWidth)
    {
        renderIcon (iconPath, iconWidth);
        
        String s=formatText(labelWidth, text, false);

        this.text.setText(s);               
    }
    
    public void renderText(char charToRender, int iconWidth)
    {
        icon.setTextToRender(charToRender+"");
        icon.setPreferredSize(new Dimension(iconWidth, iconWidth));
        icon.repaint();
    }
    
    public void updatePanel(String text, char charToRender, int iconWidth, int labelWidth)
    {
        renderText(charToRender, iconWidth);
        
        String s=formatText(labelWidth, text, true);
        this.text.setText(s);               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
