/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.UI.Components;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GraphicsEnvironment;
import java.awt.RenderingHints;
import java.awt.Transparency;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import javax.imageio.ImageIO;

/**
 *
 * @author crimsiris
 */
public class ImageIconPanel extends IconPanel {

    /**
     * Creates new form ImageIconPanel
     */
    public ImageIconPanel() 
    {
        super();
        initComponents();

    }
        
    private BufferedImage paintTranslucentImage(int width, int height)
    {
        return GraphicsEnvironment.getLocalGraphicsEnvironment().
                getDefaultScreenDevice().getDefaultConfiguration().createCompatibleImage(width, height, Transparency.TRANSLUCENT);
    }
        
    @Override
    protected void paintComponent(Graphics g) 
    {
        super.paintComponent(g);
        
        int panelWidth=getPreferredSize().width;
        int panelHeight=getPreferredSize().height;
        
        BufferedImage translucentImage=paintTranslucentImage(panelWidth, panelHeight);
        Graphics2D g2d = translucentImage.createGraphics();
        
        g2d.setComposite(AlphaComposite.Clear);
        g2d.fillRect(0, 0, panelWidth, panelHeight);
        
        g2d.setComposite(AlphaComposite.Src);
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.setColor(iconBGColor);
        g2d.fillRect(0, 0, panelWidth, panelHeight);
       
        
        if (icon!=null)
        {
            int iconWidth=icon.getWidth();
            int iconHeight=icon.getHeight();
        
            g2d.setComposite(AlphaComposite.SrcAtop);
            
            if (iconWidth<panelWidth && iconHeight<panelHeight)
            {
                int x=(panelWidth/2)-(iconWidth/2);
                int y=(panelHeight/2)-(iconHeight/2);
                g2d.drawImage(icon, x, y, iconWidth, iconHeight, null);
            }
            else
            {
                g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BICUBIC);
                g2d.drawImage(icon, 0, 0, panelWidth, panelHeight, null);
            }
        }
        
        g2d.dispose();
        g.drawImage(translucentImage, 0, 0, this);
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
