/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.UI.Components;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author crimsiris
 */
public class PageIllustrationPanel extends javax.swing.JPanel {

    private BufferedImage illustration=null;
        
    /**
     * Creates new form PageIllustrationPanel
     */
    public PageIllustrationPanel() {
        initComponents();
    }
    
    public void setIllustration(String path)
    {
        try
        {
            if (path!=null && !path.isEmpty())
            {
                illustration = ImageIO.read(new File(path));
            }  
            else
            {
                illustration=null;
                this.setBackground(Color.WHITE);
            }
        }
        catch (IOException e)
        {
            illustration=null;
            this.setBackground(Color.WHITE);
            if (Main.Debug.debug) System.out.println("error");
        }
    }
    
    @Override
    protected void paintComponent(Graphics g) 
    {
        super.paintComponent(g);

        int panelWidth=getPreferredSize().width;
        int panelHeight=getPreferredSize().height;
        
        Graphics2D g2d = (Graphics2D) g;

        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        if (illustration!=null)
        {       
            int illustrationWidth=illustration.getWidth();
            int illustrationHeight=illustration.getHeight();
        
            if (illustrationWidth<panelWidth && illustrationHeight<panelHeight)
            {
                int x=(panelWidth/2)-(illustrationWidth/2);
                int y=(panelHeight/2)-(illustrationHeight/2);
                g2d.drawImage(illustration, x, y, illustrationWidth, illustrationHeight, null);
            }
            else
            {
                g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BICUBIC);
                g2d.drawImage(illustration, 0, 0, panelWidth, panelHeight, null);
            }
        }
        
        g2d.dispose();
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
