/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.UI.Components;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JPanel;

/**
 *
 * @author crimsiris
 */
public class StatementDialoguePanel extends JPanel {

    private final int BUBBLE_WIDTH=466;
    private final int BUBBLE_HEIGHT=118;
    
    private final int BUBBLE_CURVE=30;
    
    private final int[] TRIANGLE_X_POINTS=new int[]{4, 15, 15};
    private final int[] TRIANGLE_Y_POINTS=new int[]{55, 45, 65};
    
    private final Color BGCOLOR=new Color(135,206,250); // light sky blue
    
    private final String HTML_TEXT = "<html>" +
                                        "<div style=\"width:%dpx;padding-left:%dpx;text-align:justify;\">" +
                                            "<p style=\"font-family:Edmondsans;font-size:14px;\">%s</p>" +
                                        "</div>" +
                                      "</html>";
    private final int LABEL_WIDTH=350;
    
    /**
     * Creates new form StatementDialoguePanel
     */
    public StatementDialoguePanel() 
    {
        initComponents();
        initializeComponents();
    }
    
    private void initializeComponents()
    {
        this.setBackground(Color.WHITE);
        
        bubblePanel.initializeComponents(new Dimension(BUBBLE_WIDTH, BUBBLE_HEIGHT), new Dimension(BUBBLE_CURVE, BUBBLE_CURVE), TRIANGLE_X_POINTS[1]-1, TRIANGLE_X_POINTS, TRIANGLE_Y_POINTS, BGCOLOR);
        bubblePanel.repaint();
    }
    
    private String formatText(String text)
    {
        return String.format(HTML_TEXT, LABEL_WIDTH, TRIANGLE_X_POINTS[0]*6, text);
    }
    
    public void setText(String statement)
    {
        String s=formatText(statement);
        (this.text).setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bubblePanel = new Main.UI.Components.SpeechBubblePanel();
        text = new javax.swing.JLabel();

        text.setText("jLabel1");

        org.jdesktop.layout.GroupLayout bubblePanelLayout = new org.jdesktop.layout.GroupLayout(bubblePanel);
        bubblePanel.setLayout(bubblePanelLayout);
        bubblePanelLayout.setHorizontalGroup(
            bubblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(text, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );
        bubblePanelLayout.setVerticalGroup(
            bubblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(text, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(bubblePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(bubblePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Main.UI.Components.SpeechBubblePanel bubblePanel;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
