/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.UI.Components;

import Main.Components.StoryProfile;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.JLabel;

/**
 *
 * @author crimsiris
 */
public class StoryInfoPanel extends javax.swing.JPanel {
    
    private final String HTML_STORY_TITLE = "<html>" +
                                            "<div style=\"width:%dpx;padding-left:5px;text-align:justify;\">" +
                                                "<p style=\"font-family:Edmondsans;font-size:22px;\">%s</p>" +
                                            "</div>" +
                                          "</html>";
    
    private final String HTML_STORY_TITLE_AND_SUMMARY = "<html>" +
                                                    "<div style=\"width:%dpx;padding-left:5px;text-align:justify;\">" +
                                                        "<p style=\"font-family:Edmondsans;font-size:22px;\">%s</p>" +
                                                        "<p style=\"font-family:Edmondsans;font-size:12px;\">%s</p>" +
                                                    "</div>" +
                                                 "</html>";
    
    private JLabel text;
    private ImageIconPanel icon;
    
    /**
     * Creates new form StoryInfoPanel
     */
    public StoryInfoPanel() {
        initComponents();
        
        initializeComponents();
    }
    
    private void initializeComponents()
    {
        text=new JLabel();
        text.setHorizontalAlignment(JLabel.LEADING);
        text.setVerticalAlignment(JLabel.CENTER);
        
        icon=new ImageIconPanel();
        
        this.setLayout(new FlowLayout(FlowLayout.CENTER));
        this.setBackground(Color.WHITE);
        
        this.add(icon);
        this.add(text);
    }
    
    private String formatText(int labelWidth, String text, String subtitle)
    {
        return String.format(HTML_STORY_TITLE_AND_SUMMARY, labelWidth, text, subtitle);
    }
    
    private String formatText(int labelWidth, String text)
    {
        return String.format(HTML_STORY_TITLE, labelWidth, text);
    }
    
    public void updatePanel(StoryProfile story, int iconWidth, int labelWidth)
    {
        if (story!=null)
        {
            this.icon.setIcon(story.getIconPath());
            icon.setPreferredSize(new Dimension(iconWidth, iconWidth));
            icon.repaint();
            
            String s=formatText(labelWidth, story.getTitle(), story.getSummary());
            
            this.text.setText(s);
            
        }
    }
    
    public void updatePanel(String title, String iconPath, int iconWidth, int labelWidth)
    {
        if (title!=null)
        {
            this.icon.setIcon(iconPath);
            icon.setPreferredSize(new Dimension(iconWidth, iconWidth));
            icon.repaint();
            
            String s=formatText(labelWidth, title);
            
            this.text.setText(s);
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
