/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.UI.Components;

import java.awt.Color;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;



/**
 *
 * @author crimsiris
 */
public final class VectorIconPanel extends IconPanel {
    
    /**
     * Creates new form VectorIconPanel
     */
    public VectorIconPanel() 
    {
        super();
        initComponents();  
    } 
    
    public void resetIconBGColor()
    {
        iconBGColor=getRandomColor();
    }
    
    @Override
    protected void paintComponent(Graphics g) 
    {
        super.paintComponent(g);       
        
        int panelWidth=getPreferredSize().width;
        int panelHeight=getPreferredSize().height;
        
        Graphics2D g2d = (Graphics2D) g;
        
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        g2d.setColor(iconBGColor);
        g2d.fillOval(0, 0, panelWidth, panelHeight);
        
        if (icon!=null)
        {    
            int iconWidth=icon.getWidth();
            int iconHeight=icon.getHeight();
        
            if (iconWidth<panelWidth && iconHeight<panelHeight)
            {
                int x=(panelWidth/2)-(iconWidth/2);
                int y=(panelHeight/2)-(iconHeight/2);
                g2d.drawImage(icon, x, y, iconWidth, iconHeight, null);
            }
            else
            {    

                iconWidth=getPreferredSize().width/8*7;
                iconHeight=getPreferredSize().height/8*7;
                
                int x=(panelWidth/2)-(iconWidth/2);
                int y=(panelHeight/2)-(iconHeight/2);
                              
                g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BICUBIC);
                g2d.drawImage(icon, x, y, iconWidth, iconHeight, null);
              
            }
        }
        
        if (textToRender!=null)
        {
            g2d.setFont(font);
            g2d.setColor(Color.WHITE);
            
            FontMetrics metrics=g2d.getFontMetrics(font);
            int textWidth=metrics.stringWidth(textToRender);
            
            int x=(panelWidth/2)-(textWidth/2);
            int y=panelHeight/4*3;

            g2d.drawString(textToRender, x, y);
        }
        
        g2d.dispose();
        
        
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
